### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by uvarenkovserf** [balasankarc/gemfileparser#1]
I get `list index out of range` exception when try to parse this file:
https://github.com/plataformatec/devise/blob/master/Gemfile (looks like it happens because there is no '.gemspec' file in a folder.

**Comment by balasankarc** [comment]
@uvarenkovserf Yes. Actually that may also be a bug. The current logic is that, if Gemfile references a gemspec file, it should be present in the folder. But how "references" is defined is actually incorrect. As of now, I just checks if a line starts with the work "gemspec" and infers it as a reference. However, that may not always be the case.

I am not sure when I will be able to find time to fix that, but I will definitely add it to my to-do. In the mean time, PRs are welcome. :)

**Comment by uvarenkovserf** [comment]
Good :)

**Comment by uvarenkovserf** [comment]
Also, for https://github.com/jekyll/jekyll/blob/master/Gemfile#L31 this dependency, your parser saves a dependency by name `jruby-openssl if RUBY_ENGINE ` instead of just `jruby-openssl`.

**Comment by uvarenkovserf** [comment]
And for this line https://github.com/jekyll/jekyll/blob/master/Gemfile#L29 dependency is named `File.dirname`.
