### ISSUE TITLE
License for use as a library?

### ISSUE THREAD

**Issue by pombredanne** [balasankarc/gemfileparser#4]
@balasankarc This is a request to ask if you could consider may be using an alternative license such that your code could be used as a library in a non-GPL project, possibly an LGPL?
I have already built a Gemfile.lock parser here https://github.com/nexB/scancode-toolkit-contrib/tree/develop/src/packagedcode2 and also a Ruby-based parser that spawn from Python for gemspec, but I would very much prefer using a pure Python approach.

Thank you for your kind consideration!

**Comment by balasankarc** [comment]
@pombredanne While I prefer a copyleft license for the code I write, I will surely consider your request. I am currently making some base level changes and code cleaning in the [dev branch](https://github.com/balasankarc/gemfileparser/tree/dev) as well as adding a more conclusive test suite. I intend to finish that over next weekend. Once I do that and test it out, I will release a new version which I will think about relicensing, or dual-licensing. 

To be honest, I never expected anyone else to use this code. 😁

**Comment by pombredanne** [comment]
@balasankarc Thanks!

**Comment by pombredanne** [comment]
@balasankarc kind ping... any update there? I am about to turn on Gem support in ScanCode and I would rather drop this Ruby script https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/rubygems_dumpspec.rb and use a Python solution.  BTW, tell me if you prefer instead tracking things at  https://gitlab.com/balasankarc/gemfileparser

**Comment by balasankarc** [comment]
@pombredanne I never got time to complete the work in dev. I just tagged the latest master as 0.7.0, with dual licensing - GPLv3 and MIT. I believe that should be enough for you.

**Comment by pombredanne** [comment]
@balasankarc that's plenty enough. Thanks!
